stages:
  - release

include:
  - project: 'bilimmedia/devops/devops_nodb/infra/ci-templates'
    file: '/helm/release.yml'

release:
  extends: .release-helm-template
  variables:
    HELM_PACKAGE_OUTPUT: "helm/outputs"
    HELM_CHANNEL: stable
  workflow:
    - if $CI_COMMIT_BRANCH == "master" or $CI_COMMIT_BRANCH == "main"