stages:
  - release

include:
  - project: 'bilimmedia/devops/devops_nodb/infra/ci-templates'
    file: '/helm/release.yml'

default:
  interruptible: true
  retry:
    max: 2
    when:
      - runner_system_failure
      - api_failure
  tags:
    - nodb

release:
  stage: release
  extends: .release-helm-template
  variables:
    HELM_PACKAGE_OUTPUT: "helm/outputs"
    HELM_CHANNEL: stable
    CHART_PATH: charts/default-app
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main"'
      when: always