{{ include "external-secrets.checkCRD" . }}
{{- range .Values.externalSecrets }}
{{- if .enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ .name }}"
  namespace: {{ include "default-app.namespace" $ }}
  labels:
    {{- include "default-app.labels" $ | nindent 8 }}
spec:
  refreshInterval: {{ .refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .secretStoreName | default "default-secret-store" }}
    kind: {{ .kind | default "SecretStore" }}
  target:
    name: "{{ .k8sSecretName | default .name }}"
    creationPolicy: Merge
    deletionPolicy: Retain
    template:
      metadata:
        annotations: {}
        labels: {}
      {{- if .templateData }}
      data:
        {{- toYaml .templateData | nindent 8 }}
      {{- end }}
  {{- if .templateFrom }}
  templateFrom:
    - configMap:
        name: "{{ .templateFrom.configMap }}"
        items:
          - key: "{{ .templateFrom.key }}"
  {{- end }}
  {{- if .data }}
  data:
    {{- range .data }}
    - secretKey: "{{ .secretKey }}"
      remoteRef:
        key: "{{ .remoteKey }}"
        {{- if .property }}
        property: "{{ .property }}"
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if .dataFrom }}
  dataFrom:
    - extract:
        key: "{{ .dataFrom.key }}"
  {{- end }}
{{- end }}
{{- end }}