{{- if and .Values.persistent .Values.persistent.pvc .Values.persistent.pvc.enabled }}
{{- range .Values.persistent.pvc.claims }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ include "default-app.namespace" $ }}
  labels:
    {{- include "default-app.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- .accessModes | default (list "ReadWriteOnce") | toYaml | nindent 4 }}
  {{- if .volumeMode }}
  volumeMode: {{ .volumeMode }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size | default "1Gi" }}
  {{- if .storageClass }}
  storageClassName: {{ .storageClass }}
  {{- else if and (.Values.persistent.pv.volumes | default list) (index .Values.persistent.pv.volumes 0).name }}
  volumeName: {{ (index .Values.persistent.pv.volumes 0).name }}
  {{- end }}
{{- end }}
{{- end }}