{{- if .Values.persistent.pv.enabled }}
{{- range .Values.persistent.pv.volumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .name }}
    labels:
        {{- include "default-app.labels" $ | nindent 4 }}
    {{- with .annotations }}
    annotations:
        {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
    capacity:
        storage: {{ .size }}
    {{- if .volumeMode }}
    volumeMode: {{ .volumeMode }}
    {{- end }}
    accessModes:
        {{- toYaml .accessModes | nindent 2 }}
    persistentVolumeReclaimPolicy: {{ .reclaimPolicy }}
    {{- if .storageClass }}
    storageClassName: {{ .storageClass }}
    {{- end }}
    {{- if .nodeAffinity }}
    nodeAffinity:
        required:
        nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                operator: In
                values:
                    {{- toYaml .nodeAffinity | nindent 16 }}
    {{- end }}
    {{- if .hostPath}}
    hostPath:
        path: {{ .hostPath}}
    {{- end }}
{{- end }}
{{- end }}