apiVersion: v1
kind: Service
metadata:
  name: "{{ include "default-app.fullname" . }}-svc"
  namespace: {{ include "default-app.namespace" . }}
  labels:
    {{- include "default-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "default-app.selectorLabels" . | nindent 4 }}