{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "default-app.fullname" . }}-cm"
  namespace: {{ include "default-app.namespace" . }}
  labels:
    app: {{ include "default-app.name" . }}
    app.kubernetes.io/name: {{ include "default-app.name" . }}
    {{- include "default-app.labels" . | nindent 4 }}
data:
  {{ .Values.configMapFile }}: |-
    {{- .Values.config | toYaml | nindent 4 }}
{{- end }}