{{- range .Values.configs }}
{{- if .enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .name }}"
  namespace: {{ include "default-app.namespace" $ }}
  labels:
    {{- include "default-app.labels" $ | nindent 4 }}
data:
  {{- if .useEnvFrom }}
    {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- else }}
  {{ .fileName }}: |-
{{ .data | indent 4 }}
  {{- end }}
{{- end }}
{{- end }}