{{ include "external-secrets.checkCRD" . }}
{{- if (default .Values.externalSecrets.enabled true) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "default-app.externalSecretName" . }}
  namespace: {{ include "default-app.namespace" . | default "default" }}
  labels:
    {{- include "default-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName | default "default-secret-store" }}
    kind: {{ .Values.externalSecrets.kind | default "SecretStore" }}
    namespace: {{ .Values.externalSecrets.secretStoreNamespace | default "default" }}
  target:
    name: {{ .Values.externalSecrets.k8sSecretName | default "default-secret" }}
  data:
    - secretKey: {{ .Values.externalSecrets.secretKey | default "default-key" }}
      remoteRef:
        key: {{ .Values.externalSecrets.lockboxSecretID | default "default-id" }}
        {{- if .Values.externalSecrets.propertyName }}
        property: {{ .Values.externalSecrets.propertyName | default "default-property" }}
        {{- end }}
{{- end }}