apiVersion: v1
kind: Secret
metadata:
  name: {{ include "default-app.fullname" . }}
  namespace: {{ include "default-app.namespace" . }}
  labels:
    {{- include "default-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  sensitive-key: "sensitive-value"