{{- range .Values.secrets }}
{{- if .enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .name }}"
  namespace: {{ include "default-app.namespace" $ }}
  labels:
    {{- include "default-app.labels" $ | nindent 4 }}
type: Opaque
stringData:
{{- if .envFrom }}
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- else }}
  {{ .fileName }}: |-
{{ .data | indent 4 }}
{{- end }}
{{- end }}
{{- end }}