{{- if .Values.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "default-app.fullname" . }}-secret"
  namespace: {{ include "default-app.namespace" . }}
  labels:
    {{- include "default-app.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}