name: Update Helm Repo Index

on:
  workflow_run:
    workflows: ["Release Helm Chart"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Chart Releaser
        run: |
          ARCH=$(uname -m)
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          CR_VERSION=$(curl -s https://api.github.com/repos/helm/chart-releaser/releases/latest | grep '"tag_name"' | cut -d '"' -f 4)
          CR_BINARY="chart-releaser_${OS}_${ARCH}"
          
          curl -sSL -o cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/${CR_VERSION}/${CR_BINARY}.tar.gz"
          tar -xzf cr.tar.gz
          chmod +x cr
          sudo mv cr /usr/local/bin/
          
          cr --version

      - name: Run Chart Releaser Index
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          cr index --owner "${{ github.repository_owner }}" --git-repo "$(basename ${{ github.repository }})" --packages-with-index --index-path . --token "${{ secrets.GITHUB_TOKEN }}" --push

      - name: Commit and push changes
        run: |
          git add index.yaml
          git commit -m "Update Helm repo index"
          git push origin gh-pages