name: Update Helm Repo Index

on:
  workflow_run:
    workflows: ["Release Helm Chart"]
    types:
      - completed

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Chart Releaser
        run: |
          ARCH=$(uname -m)
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          CR_VERSION=$(curl -s https://api.github.com/repos/helm/chart-releaser/releases/latest | jq -r '.tag_name')

          if [[ "$ARCH" == "x86_64" ]]; then ARCH="amd64"; fi
          if [[ "$ARCH" == "aarch64" ]]; then ARCH="arm64"; fi

          CR_BINARY="chart-releaser_${CR_VERSION}_${OS}_${ARCH}.tar.gz"
          DOWNLOAD_URL="https://github.com/helm/chart-releaser/releases/download/v${CR_VERSION}/${CR_BINARY}"

          echo "Downloading Chart Releaser from $DOWNLOAD_URL"
          if ! curl --head --fail --silent "$DOWNLOAD_URL"; then
            echo "Error: The requested file does not exist at $DOWNLOAD_URL"
            exit 1
          fi
          
          curl -fsSL -o cr.tar.gz "$DOWNLOAD_URL"
          tar -xzf cr.tar.gz
          chmod +x chart-releaser
          sudo mv chart-releaser /usr/local/bin/cr

          echo "Chart Releaser installed successfully:"
          cr --version

      - name: Run Chart Releaser Index
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          cr index --owner "${{ github.repository_owner }}" --git-repo "$(basename ${{ github.repository }})" --packages-with-index --index-path . --token "${{ secrets.GITHUB_TOKEN }}" --push

      - name: Commit and push changes
        run: |
          git add index.yaml
          git commit -m "Update Helm repo index"
          git push origin gh-pages